.Dd May 22, 2024
.Dt SNDFILE-JACKPLAY 1
.Os
.Sh NAME
.Nm sndfile-jackplay
.Nd play a sound file via the JACK sound server
.Sh SYNOPSIS
.Nm
.Op Fl a Op Ar port
.Op Fl h
.Op Fl l Op Ar count
.Op Fl w Op Ar port
.Ar file
.Sh DESCRIPTION
.Nm
plays the specified sound file via the JACK sound server.
It uses libsndfile to read the file.
.Pp
The options are as follows:
.Pp
.Bl -tag -compact -width wportxxxxx
.It Fl a Op Ar port
Auto-connect to
.Ar port
using Jack.
.It Fl h
Print a help message and exit.
.It Fl l Op Ar count
Loop the file
.Ar count
times, where 0 means an infinite loop.
.It Fl w Op Ar port
Wait for input before starting playback.
.El
.Sh SEE ALSO
.Lk http://libsndfile.github.io/libsndfile/
.Sh AUTHORS
.An Erik de Castro Lopo Aq Mt erikd@mega-nerd.com
