.Dd May 22, 2024
.Dt SNDFILE-GENERATE-CHIRP 1
.Os
.Sh NAME
.Nm sndfile-generate-chirp
.Nd create a sound file containing a swept sine wave
.Sh SYNOPSIS
.Nm
.Op Fl h
.Op Fl from Ar start
.Op Fl to Ar end
.Op Fl amp Ar value
.Op Fl log
.Op Fl quad
.Op Fl linear
.Ar rate
.Ar length
.Ar file
.Sh DESCRIPTION
.Nm
generates a sound file containing a sine wave
that sweeps from a low starting frequency to a higher ending frequency.
The file is written using libsndfile.
.Pp
The output file will contain floating point samples between -1 and 1.
The output file type is determined by the file name extension
which should be one of
.Sq wav ,
.Sq aifc ,
.Sq aif ,
.Sq aiff ,
.Sq au ,
.Sq caf
or
.Sq w64 .
.Pp
The options are as follows.
.Pp
.Bl -tag -compact -width fromxstartx
.It Fl h
Print a help message and exit.
.It Fl from Ar start
Sweep start frequency in Hz (default 200Hz).
.It Fl to Ar end
Sweep end frequency in Hz (default rate/2).
.It Fl amp Ar value
Amplitude of generated sine (default 1.0).
.It Fl log
Use a logarithmic sweep (the default).
.It Fl quad
Use a quadratic sweep.
.It Fl linear
Use a linear sweep.
.El
.Sh SEE ALSO
.Lk https://github.com/libsndfile/
.Sh AUTHORS
.An Erik de Castro Lopo Aq Mt erikd@mega-nerd.com
