.Dd May 22, 2024
.Dt SNDFILE-MIX-TO-MONO 1
.Os
.Sh NAME
.Nm sndfile-mix-to-mono
.Nd mix a multi-channel sound file to mono
.Sh SYNOPSIS
.Nm
.Ar ifile
.Ar ofile
.Sh DESCRIPTION
.Nm
reads a multi-channel input file and writes a single-channel output file
consisting of all of the input channels mixed into one.
The files are read and written using libsndfile.
The format of the output file is determined by its filename extension.
.Sh SEE ALSO
.Lk https://github.com/libsndfile/
.Sh AUTHORS
.An Erik de Castro Lopo Aq Mt erikd@mega-nerd.com
